### PR TITLE
Fix windows install and clean up README

### PR DESCRIPTION
**Pull request by musm**
Close
https://github.com/JuliaInterop/MATLAB.jl/issues/23
https://github.com/JuliaInterop/MATLAB.jl/issues/50

### CODE REVIEW

**Comment by simonster** [comment]
Thanks!

**Comment by musm** [comment]
Simon, could I be added to JuliaInterop?

**Comment by musm** [comment]
Also @ChrisRackauckas  requested to be added as well. He said he could help with tagging a new version.

**Comment by musm** [comment]
I'm updating the package. So the plan is to first tag the current version, before taging a new version with the update and then renaming to MatlabCall.jl

**Comment by simonster** [comment]
You two should both have access now.

**Comment by musm** [comment]
@simonster thank you!
@ChrisRackauckas do you mind tagging the current version, before the upcoming changes, thank you again!

**Comment by ChrisRackauckas** [comment]
Will do.

**Comment by musm** [comment]
Fantastic thanks!

**Comment by musm** [comment]
I just realized that I don't know we will be able to fork and create repos (for the MATLAB.jl rename) since we're not in JuliaInterop.

**Comment by ChrisRackauckas** [comment]
I also don't have sufficient permissions to push the tag...

permissions

**Comment by simonster** [comment]
I'd prefer to do the move myself. I can go ahead and do it now unless there are objections.

**Comment by ChrisRackauckas** [comment]
I pushed the tag. All is in METADATA. You're good to go.

**Pull request merged**
