### PR TITLE
Better error for failed MEngine session

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaInterop/MATLAB.jl/issues/115

### CODE REVIEW

**Comment by musm** [comment]
any comments?

**Comment by musm** [comment]
@ChrisRackauckas if it's annoying I can stop :)

**Comment by musm** [comment]
By that I mean always pinging you for review requests 😄

**Comment by ChrisRackauckas** [comment]
No worries, it's fine. These are all simple. I don't know if I truly have "authority" to merge here though.

**Comment by musm** [comment]
Thanks, I just want to have another set of eyes on this, before I merge in a day or so.

**Pull request merged**
