### PR TITLE
README: add two toolbox-related links

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by musm** [comment]
@waldyrious I feel like we should close this. I don't think it's adding anything valuable that MATLAB users wouldn't be aware of.

**Comment by ChrisRackauckas** [comment]
>@waldyrious I feel like we should close this. I don't think it's adding anything valuable that MATLAB users wouldn't be aware of.

I definitely agree. This is a package for using MATLAB from Julia, not an advertisement of what MATLAB offers. If anything, the README should be shorted to just be about the interop, and not even explain what Julia is. Julia packages don't need a link to julialang in the readme...

**Comment by waldyrious** [comment]
I could agree if this change entailed adding a couple sentences or paragraphs of additional information, but it kept the (at the time) wording intact, only adding contextual links which made things explicit, and could be helpful for those taking their first steps in MATLAB and/or Julia. I can't see how less/implicit information is preferable to more/explicit information, especially if this doesn't come at the expense of additional text.

That said, considering that the paragraph that this PR modifies has been removed in #55, adding these links now would indeed require adding additional text. So I'll agree to closing for this reason, but will kindly ask you to reconsider your approach to documentation (the "everyone already knows this" stance) to [keep beginners in mind](https://xkcd.com/1053/), or even people who come across these packages from different routes than what you expect.

**Comment by ChrisRackauckas** [comment]
>but will kindly ask you to reconsider your approach to documentation (the "everyone already knows this" stance)

It's not an "everyone already knows this stance", it's keeping irrelevant information out of the documentation. Of course, every Julia package could have a paragraph on what Julia is, why you should use it, point you to the download link, etc., but at some point it's too much information and actually just gets in the way. In this case, this is a package about interop between Julia and MATLAB. Describing what you can do with Julia and what you can do with MATLAB is out of the scope and clutters the main message, which is "can you control MATLAB from Julia and how do you do it?" and not "what can you do with MATLAB?".

**Comment by waldyrious** [comment]
> every Julia package could have a paragraph on what Julia is, why you should use it, point you to the download link, etc., but at some point it's too much information and actually just gets in the way.

Agreed, hence the change here only includes links, not additional text. Links, `<abbr>` tags, link titles (tooltips) are great ways to provide contextual information without getting in the way :)

I do think a julia package should at least mention Julia, and having a link to it in that word only has upsides, I think.

> Describing what you can do with Julia and what you can do with MATLAB

Just to reinforce my point, I'm not defending *adding* such information. I merely added links to information that was already present. As I said above, "adding these links *now* would indeed require adding additional text. So I'll agree to closing for this reason". So we're in agreement on that point.

**Comment by musm** [comment]
@waldyrious  Thanks for this, yeah I agree these changes would have been good before the update to the README since the only thing that they did is to add more information via tooltip links. Thanks.

**Comment by waldyrious** [comment]
I'm glad you understand :) I'll close this PR as it doesn't apply anymore.

**Pull request closed without merging**
