### PR TITLE
Use transcode for string convert to Julia

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by simonster** [comment]
I'm not sure we can assume characters are always UTF-16. In R2015a+ we should probably use [mxArrayToUTF8String](https://www.mathworks.com/help/matlab/apiref/mxarraytoutf8string.html) since it is guaranteed to handle the locale properly.

**Comment by musm** [comment]
http://www.ece.northwestern.edu/local-apps/matlabhelp/techdoc/apiref/mxchar.html

Also mxarray('a') was also broken

**Comment by simonster** [comment]
Just because MATLAB is storing characters as 16-bit integers does not necessarily mean it's encoding them as UTF-16, which is what `transcode` assumes.

**Comment by simonster** [comment]
Although http://www.mathworks.com/help/matlab/apiref/mxchar.html suggests it is UTF-16 (really UCS-2) at least on new-ish MATLAB, so maybe this is okay.

**Comment by musm** [comment]
people on version older than 2006 are out of luck, I think that's fine since it's 10 years old at this point

**Comment by simonster** [comment]
I think there are versions newer than 2006 that don't use UTF-16 internally (mxChar was introduced before 2006a, but looking around online it's clear it wasn't always defined to be Unicode), but I don't think there's a convenient way to convert their internal encodings to UTF-8, and 16-bit ISO-8859-1 is basically the same as UTF-16, so I'm fine with this.

**Comment by musm** [comment]
we might have to revert this. It's not properly handling some unicode glyphs

**Comment by twadleigh** [comment]
@musm which? It was working fine for me in `mexjulia` on my tests.

**Comment by musm** [comment]
@twadleigh  see the test added at: https://github.com/JuliaInterop/MATLAB.jl/pull/78

**Comment by twadleigh** [comment]
I can't duplicate a test failure in `mexjulia`.

If I throw the following into `Mex.jl`:
```
const funky_string = "λ α γ"
is_funky_string(str) = str == funky_string
```
and call it from MATAB, I get:
```
>> str = jl.eval('funky_string')

str =

λ α γ

>> jl.call('is_funky_string', str)

ans =

  logical

   1
```

**Pull request merged**
